name: Push Container to Heroku

#TODO: Replace by:
  #on:
  #push:
    #branches: [ main ]
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Version
        uses: actions/setup-node@v2

      #TODO unit tests
      #- name: Run tests
      #run tests

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
    - name: Run a one-line script
      run: echo successfully run
      